pipelines:
  example-pipeline:
    group: Infradel
    materials:
      mygit:
        git: https://github.com/datherra/gocd-config-repo-example.git
        branch: master
    stages:
      - test:
        approval: manual
        jobs:
          echo_test:
            tasks:
            - exec:
              command: echo
              arguments:
                - "This is an example single job stage"
